{% set name = "pytest-tornasync" %}
{% set version = "0.6.0.post2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d781b6d951a2e7c08843141d3ff583610b4ea86bfa847714c76edefb576bbe5d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - pytest
    - python
    - tornado >=5.0

test:
  imports:
    - pytest_tornasync
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/eukaryote/pytest-tornasync
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: A simple pytest plugin that provides some helpful fixtures for testing Tornado (version 5.0 or newer) apps and easy handling of plain (undecoratored) native coroutine tests (Python 3.5+).
  summary: py.test plugin for testing Python 3.5+ Tornado code
  dev_url: https://github.com/eukaryote/pytest-tornasync
  doc_url: https://github.com/eukaryote/pytest-tornasync/blob/master/README.rst

extra:
  recipe-maintainers:
    - lincrosenbach
    - igorcandeia
    - kfasolin
    - nicoddemus
