travis:
  secure:
    BINSTAR_TOKEN: JxkFtaLRYdX0ppxitd4LNNaoFm0JNe5Csbi+AR8XAmCHKZSgITYKVCkl5Sy9JiXWKjI4Cd9h9ycGMYB6X0xDMS0feACzhQBDxrj3G99d8R8Tot7I1lUYMO4Abp77MXra0rY30FHI7pW+j1CvH4uWEv0ad1u09FGJTnQRbkFTQjJc+Tl8VChoTWVEExO++FJXisDPQGQ20lFUj/Gqr01vy7WmlGXyr8Q5847paM2rdXTO/cgHfvbzHj+U+1qo2BcfKTYcKGrPs8r7Up9HNXQMrZ2kOqkp1bLPaC6j1lAnbJnzVntUw+J/ucQGK+J8TxIzN8KmMRmJC2vbQMdEKj5TrjdXNVTqT2/o8rL7KjjXS8bMYKHIpdlguq5/5kLADRM4c3xRXOUoxscWSwbKFTYjw5mhvyIMIHNLDrPWUifdPMekQK2vBNxPzm1CT+mbXKCL1DfH7So3wHre60GOPMIDIhSNnv4WSpi9/c0kMf6og6wovFqwkrQfyH/pHcAfZZBX5uzyFK5srs4toG/G7XOXAuXPqCOYs9R7Z4PVdKiq5QgD4E3+MdsiE7uvsYYU9NJUhC0c6qpA0/sV6HH2DzakK0JPl3EFyH5S0vV8+CPMDLwFnW12mWIyHMQYW7uDhcGSoFzq79DuZ7OkUBUWvth5oZwRMnAnkPV7S0iW02qWPR4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
